var key = 'supersecretkeyhjshdkjhas'
var message = 'The quick brown fox jumps over the lazy dog'
console.log('key: ' + key)
console.log('message: ' + message)
document.write('key: ' + key + '<br>')
document.write('message: ' + message + '<br>')
var hmac = forge.hmac.create()
hmac.start('sha1', key)
hmac.update(message)
console.log('HMAC-SHA1: ' + hmac.digest().toHex())
document.write('HMAC-SHA1: ' + hmac.digest().toHex() + '<br>')
var hmac = forge.hmac.create()
hmac.start('sha256', key)
hmac.update(message)
console.log('HMAC-SHA256: ' + hmac.digest().toHex())
document.write('HMAC-SHA256: ' + hmac.digest().toHex() + '<br>')
var hmac = forge.hmac.create()
hmac.start('sha512', key)
hmac.update(message)
console.log('HMAC-SHA512: ' + hmac.digest().toHex())
document.write('HMAC-SHA512: ' + hmac.digest().toHex() + '<br>')
